spec_id: CODING-STANDARDS
name: "JavaScript Functional Coding Standards"

files:
  - name: llm-loader.md
    role: llm_bootstrap
  - name: logic.yaml
    role: implementation_rules
  - name: tests.yaml
    role: validation_suite