spec_id: F110
name: "Migrate SegmentedCurbEditor to Design System"

files:
  - name: llm-loader.md
    role: llm_bootstrap
  - name: logic.yaml
    role: implementation_rules
  - name: tests.yaml
    role: validation_suite 