spec_id: SPEC-FORMAT
name: "Specification Format Standard"
description: "Defines required files and structure for all specifications"

files:
  - name: llm-loader.md
    role: llm_bootstrap
  - name: logic.yaml
    role: implementation_rules
