spec_version: 1.0
spec_id: A005
name: Git Commit Message Format
type: system
status: active

files:
  - name: llm-loader.md
    role: llm_bootstrap
  - name: logic.yaml
    role: implementation_rules
  - name: tests.yaml
    role: validation_suite