/*
 * Infrastructure Plan Type
 *
 * Represents a complete execution plan with steps generated by adapters.
 * Plans are immutable once created and contain all information needed
 * for execution and audit logging.
 */

// prettier-ignore
export const InfrastructurePlan = {
    name: 'InfrastructurePlan',
    kind: 'tagged',
    fields: {
        id       : 'String',
        operation: 'String',
        config   : 'Object?',
        steps    : '[InfrastructureStep]',
    },
}
