spec_id: F108
name: "Infrastructure Testing Strategy - Phase 1: Test Adapter Foundation"

files:
  - name: llm-loader.md
    role: llm_bootstrap
  - name: logic.yaml
    role: implementation_rules
  - name: tests.yaml
    role: validation_suite