# docs/solutions/ Frontmatter Schema
#
# Simple format used by all existing docs. Grep-searchable fields.

required_fields:
  title:
    type: string
    description: "Clear problem title"

  date:
    type: string
    pattern: '^\d{4}-\d{2}-\d{2}$'

  category:
    type: enum
    values:
      - architecture
      - runtime-errors
      - test-failures
      - integration-issues
      - workflow-issues

  module:
    type: string
    description: "Module name (e.g., quicken-web-app, functional, keymap) or System"

  tags:
    type: array[string]
    max_items: 8
    description: "Searchable keywords, lowercase, hyphen-separated"

  symptoms:
    type: array[string]
    min_items: 1
    max_items: 5
    description: "Observable symptoms — exact error messages or behavior"
