spec_id: F113
name: "Minimal Token Migration for SegmentedCurbEditor"

files:
  - name: llm-loader.md
    role: llm_bootstrap
  - name: logic.yaml
    role: implementation_rules
  - name: tests.yaml
    role: validation_suite 