spec_id: F200
name: "LookupTable Blockface Migration"

files:
  - name: llm-loader.md
    role: llm_bootstrap
  - name: logic.yaml
    role: implementation_rules
  - name: tests.yaml
    role: validation_suite
