spec_version: 1.0
spec_id: F108
name: Function Declaration Ordering Rule
type: feature
status: active

files:
  - name: llm-loader.md
    role: llm_bootstrap
    required: true
  - name: logic.yaml
    role: implementation_rules
    required: true
  - name: tests.yaml
    role: validation_suite
    required: false