spec_id: SPEC-TEMPLATE
name: "Specification Template"
type: "evergreen"
description: "Template for creating new specifications"

files:
  - name: llm-loader.md
    role: llm_bootstrap
  - name: logic.yaml
    role: implementation_rules
  - name: templates/
    role: template_files
